import Foundation

extension Gen2Pokedex {
    /// Short, original species summaries for the Johto Pokédex additions.
    public static let descriptions: [String] = [
        "A leaf on its head senses warmth and moisture, helping it find sunny places to rest.",
        "Its neck leaves release a spicy aroma that can revive tired companions.",
        "The petals around its neck release a calming fragrance as it stands in bright sunlight.",
        "Flames flare from its back when it is startled, excited, or ready to battle.",
        "It intimidates opponents with hot gusts and nimble movements before striking.",
        "A fiery Pokémon that creates shimmering heat waves and charges with explosive force.",
        "Its powerful jaws snap with surprising strength, even when it is only playing.",
        "A restless water hunter that attacks with sharp fangs and a tough hide.",
        "Its massive jaws can crush hard objects, and it moves faster in water than on land.",
        "It stands on its tail to scan tall grass and warn its group of danger.",
        "Its long, slim body lets it slip through narrow spaces while chasing prey.",
        "It keeps time with an internal rhythm and turns its head completely around to watch.",
        "Its soft wings make silent flight possible, and its eyes see clearly in darkness.",
        "A timid Pokémon that communicates with others by flashing the spots on its back.",
        "It scatters sparkling powder from its wings while punching rapidly with four arms.",
        "It spins fine silk from its mouth and waits patiently for vibrations in its web.",
        "Its horn and fangs inject venom, and its patterned body startles foes in the dark.",
        "Its extra wings give it swift, silent flight through caves and moonlit forests.",
        "Two antennae glow as it swims through dark water and releases stored electricity.",
        "Its bright lure guides it through deep seas and can attract curious prey from far away.",
        "A playful young Pokémon whose tiny cheeks leak electricity when it laughs or panics.",
        "It gathers where shooting stars fall and bounces lightly under moonlit skies.",
        "Its soft voice can soothe others, and its round body inflates when it is excited.",
        "Its shell is said to be filled with happiness, which it shares with kind people.",
        "It spreads joy by sensing good feelings and scattering a gentle, sparkling dust.",
        "Its small wings cannot carry it far, but its eyes seem to watch distant places.",
        "It stands still like a totem and is said to glimpse both the past and future.",
        "Its wool stores electricity, causing its fleece to puff up and crackle.",
        "As it stores more electricity, patches of its wool fall away and its tail glows.",
        "The bright orb on its tail can be seen from far away, even across the sea.",
        "It dances in sunlight and releases a sweet scent from the flower on its head.",
        "Its oil-coated fur repels water, and its tail works like a floating buoy.",
        "It lives comfortably in rivers, using its large ears and tail to swim with ease.",
        "It pretends to be a tree, standing motionless until rain or water gives it away.",
        "A confident swimmer whose curled hair marks it as a leader among Poliwag.",
        "Its light body drifts on warm breezes, sometimes carrying it far from home.",
        "The flower on its head opens in strong sunlight as it floats on seasonal winds.",
        "It scatters cotton spores from its body and rides the wind with remarkable control.",
        "It swings from branches with its tail and is drawn to shiny, playful objects.",
        "It stores nutrients in its seed body and perks up quickly under strong sunlight.",
        "Its face-like petals follow the sun, collecting energy throughout the day.",
        "It darts over ponds on fast wings, using its wide eyes to spot movement.",
        "This muddy Pokémon closes its nostrils underwater and enjoys cool riverbeds.",
        "It waits in water with only its head exposed, then lunges with a broad smile.",
        "Its fine fur reads air currents and sunlight, letting it predict nearby movement.",
        "It glows under moonlight and waits patiently for night to sharpen its senses.",
        "It loves glittering objects and hides them in secret places before anyone notices.",
        "A Shellder on its head boosts its intellect, making it calm and surprisingly clever.",
        "It appears in quiet places and startles people with eerie cries after sunset.",
        "Each shape acts mysteriously, as if trying to communicate through ancient symbols.",
        "It is patient and defensive, absorbing blows before striking back with stored force.",
        "Its front and rear heads watch different directions, keeping it alert at all times.",
        "It hangs from tree branches like a pinecone and layers its shell with bark.",
        "Its steel-hard shell protects it as it waits motionless for enemies to approach.",
        "It digs winding tunnels and pops up unexpectedly despite its small wings.",
        "It glides between cliffs on stretched wings and hooks prey with its tail and claws.",
        "A metal-coated body makes it tougher than rock as it tunnels deep underground.",
        "Though its face looks fierce, it is friendly and often popular with children.",
        "Its strong jaws and bold attitude let it scare off foes much larger than itself.",
        "It swallows water to inflate its body and bristle with poisonous spikes.",
        "Its metal pincers clamp with great force and display eye-like markings.",
        "It stores berries inside its shell and quietly waits in rocky hiding places.",
        "A proud forest fighter with a horn powerful enough to throw heavy opponents.",
        "It lives in cold places, stealing eggs and striking quickly with sharp claws.",
        "It loves sweet honey and practices climbing trees with its crescent-marked face.",
        "A powerful forest Pokémon that protects its territory with heavy swipes.",
        "Its molten body leaves warm trails, though it dislikes cool, damp places.",
        "Its brittle shell formed from cooled magma can crack and leak intense heat.",
        "It searches for food by rubbing its nose along frozen ground.",
        "Its long tusks and shaggy coat help it push through snow and ice.",
        "It sheds and regrows coral branches, thriving in warm, clean seas.",
        "It clings to Mantine and fires precise jets of water at passing prey.",
        "Its flexible tentacles and sharp focus let it strike targets with uncanny accuracy.",
        "It carries food in its tail and shares gifts while flying through snowy skies.",
        "It glides over ocean currents with Remoraid often traveling beneath its fins.",
        "Its steel wings are light and sharp, allowing swift flight over rugged mountains.",
        "It tracks scents in the dark and works together with its pack to hunt.",
        "Its horns and flames signal leadership, and its howl can unsettle any foe.",
        "Its coiled body creates powerful whirlpools when it moves through rough seas.",
        "It cheerfully charges forward, unaware of how strong its little body is.",
        "It digs with its trunk and can knock aside boulders with a single tackle.",
        "An upgraded virtual Pokémon that processes data more smoothly than its predecessor.",
        "Its branching antlers create subtle distortions that confuse anyone watching closely.",
        "It paints markings with tail fluid, and each Smeargle develops a unique style.",
        "It trains constantly and evolves according to the fighting talent it develops.",
        "It spins on its head with graceful kicks, balancing offense and defense.",
        "Its lips are highly sensitive, helping it inspect objects and express emotion.",
        "It stores electricity in its body and waves its arms when excited.",
        "Its body temperature runs hot, and small flames escape as it breathes.",
        "A sturdy dairy Pokémon known for nutritious milk and a gentle nature.",
        "It shares happiness and healing energy through the egg it carefully carries.",
        "A lightning-fast legendary Pokémon said to race with thunderclouds.",
        "A volcanic legendary Pokémon whose roar is said to make magma surge.",
        "A graceful legendary Pokémon associated with pure water and northern winds.",
        "It is born deep underground and eats soil before emerging to the surface.",
        "Its hard shell protects it while it gathers strength for its final evolution.",
        "A towering armored Pokémon whose steps can shake mountains and cliffs.",
        "A guardian of the seas whose wings can calm storms or whip them into tempests.",
        "A radiant legendary Pokémon whose rainbow wings are linked to renewal and hope.",
        "A time-crossing mythical Pokémon that protects forests and brings life to plants.",
    ]

    public static func description(for dex: Int) -> String? {
        guard dexRange.contains(dex) else { return nil }
        let index = dex - dexRange.lowerBound
        guard descriptions.indices.contains(index) else { return nil }
        return descriptions[index]
    }
}
